on: 
  push:
    branches: [main]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
    steps:
      - uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      
      - uses: levibostian/decaf@0.16.0
        id: decaf
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: deno task run get-latest-release
          get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
          deploy: |
            deno compile --output decaf-script-github-releases-x64-linux --target x86_64-unknown-linux-gnu script.ts
            deno compile --output decaf-script-github-releases-arm64-linux --target aarch64-unknown-linux-gnu script.ts
            deno compile --output decaf-script-github-releases-x64-macos --target x86_64-apple-darwin script.ts
            deno compile --output decaf-script-github-releases-arm64-macos --target aarch64-apple-darwin script.ts
            cp install.template install.sh
            chmod +x install.sh
            sed -i "s/PUT_VERSION_HERE/${{ steps.decaf.outputs.next_version_name }}/" install.sh
            cat install.sh | grep VERSION
            deno task run set-github-release-assets \
              decaf-script-github-releases-x64-linux \
              decaf-script-github-releases-arm64-linux \
              decaf-script-github-releases-x64-macos \
              decaf-script-github-releases-arm64-macos \
              install.sh
            deno task run set